/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adamtrcka.work;

import com.adamtrcka.work.hw.Application;


public class App {


    public static void main(String[] args) {

        Application app=new Application(args);

    }


    public double getVersion()
    {
        return 0.003;
    }


}
