/*
 * This Java source file was generated by the Gradle 'init' task.
 * Its basic expantion was made for the Dependency Manager... but really should be greatly expanded on
 * 
 */
package com.adamtrcka.work;
import com.adamtrcka.work.hw.args.ArgumentValidator;
import com.adamtrcka.work.hw.dependency.DependencyStructure;
import com.adamtrcka.work.hw.json.jsonReader;

import org.junit.Test;

import static org.junit.Assert.*;

import java.util.HashMap;

public class AppTest {
    @Test
    public void testAppHasAVersion() {
        App classUnderTest = new App();
        assertNotNull("App should have a version", classUnderTest.getVersion());
    }

    @Test
    public void testDependencyStructure()
    {
        DependencyStructure testds = new DependencyStructure();
        String key = "HELLO";
        String value = "WORLD";
        testds.addStructure(key,value);
        assertTrue("key exists in structure",testds.isExistsKey(key));
        assertTrue("value exists in structure",testds.isExistsValue(value));
    }

    @Test
    public void testArgValidator() {
        String[] str = new String[]{"filename"};
        ArgumentValidator avTest = new ArgumentValidator(str);
        assertTrue("class validate exists 0 key in array args", avTest.isValid());
    }
}
